mapping {
  map eventParameter('type') onto 'type'
  map eventParameter('category') onto 'category'
  map eventParameter('user_stone_category') onto 'user_stone_category'
  map eventParameter('user_search_bar') onto 'user_search_bar'
  map { parse eventParameter('user_user_id') to int64 } onto 'user_user_id'
  map eventParameter('user_user_name') onto 'user_user_name'
  map { parse eventParameter('user_company_id') to int64 } onto 'user_company_id'
  map eventParameter('user_company_name') onto 'user_company_name'
  map { parse eventParameter('user_product_visited_id') to int64 } onto 'user_product_visited_id'
  map eventParameter('user_product_visited_name') onto 'user_product_visited_name'
  map { parse eventParameter('user_product_visited_time') to int64 } onto 'user_product_visited_time'
  map { parse eventParameter('user_product_visited_scroll_percentage') to fp32 } onto 'user_product_visited_scroll_percentage'
  map { parse eventParameter('user_product_visited_company_id') to int64 } onto 'user_product_visited_company_id'
  map eventParameter('user_product_visited_company_name') onto 'user_product_visited_company_name'
  map eventParameter('country') onto 'country'
  map eventParameter('state') onto 'state'
  map eventParameter('city') onto 'city'
  map eventParameter('postal') onto 'postal'
  map eventParameter('latitude') onto 'latitude'
  map eventParameter('longitude') onto 'longitude'
  map eventParameter('ip') onto 'ip'
  map eventParameter('continent_code') onto 'continent_code'
  map eventParameter('continent_name') onto 'continent_name'
  map eventParameter('country_code') onto 'country_code'
  map eventParameter('region_code') onto 'region_code'
  map eventParameter('capital_city') onto 'capital_city'
  map eventParameter('language_code') onto 'language_code'
  map eventParameter('language_name') onto 'language_name'
  map eventParameter('country_flag_url') onto 'country_flag_url'
  map eventParameter('browser_name') onto 'browser_name'
  map eventParameter('browser_full_version') onto 'browser_full_version'
  map eventParameter('browser_major_version') onto 'browser_major_version'
  map eventParameter('navigator_app_name') onto 'navigator_app_name'
  map eventParameter('navigator_user_agent') onto 'navigator_user_agent'
  map eventParameter('os_name') onto 'os_name'
  map eventParameter('js_error_msg') onto 'js_error_msg'
  map eventParameter('js_error_level') onto 'js_error_level'
  map eventParameter('js_url') onto 'js_url'
  map { parse eventParameter('js_line') to int32 } onto 'js_line'
  map { parse eventParameter('js_column') to int32 } onto 'js_column'
  map { parse eventParameter('js_is_error_caught') to bool } onto 'js_is_error_caught'
}
